[versions]
agp = "8.13.1"
kotlin = "2.0.21"
xposedApi = "82"

[libraries]
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposedApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
